srswdom/recomendador/urls.py
from django.urls import path
from . import views

app_name = 'recomendador'

urlpatterns = [
    # ex: /
    path('', views.lista_usuarios, name='lista_usuarios'),
    # ex: /usuarios/
    path('usuario', views.lista_usuarios, name='lista_usuarios'),
    # ex: /usuario/5/
    path('usuario/<int:usuario_id>/', views.detalle_usuario, name='detalle_usuario'),
     # ex: /servicios/
    path('servicio', views.lista_servicios, name='lista_servicios'),
    # ex: /servicio/5/
    path('servicio/<int:servicio_id>/', views.detalle_servicio, name='detalle_servicio'),
    path('servicio/<int:servicio_id>/nueva_calificacion/',views.nueva_calificacion,name='nueva_calificacion'),
    # ex: /proveedores/
    path('proveedor', views.lista_proveedores, name='lista_proveedores'),
        # ex: /proveedor/A1244213/
    path('proveedor/<int:proveedor_id>/', views.detalle_proveedor, name='detalle_proveedor'),
     # ex: /dominios/
    path('dominio', views.lista_dominios, name='lista_dominios'),
    # ex: /servicio/5/
    path('dominio/<int:dominio_id>/', views.detalle_dominio, name='detalle_dominio'),
    # ex: /calificaciones/
    path('calificacion', views.calificaciones, name='calificaciones'),    
   ]

srswdom/srswdom/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('recomendador/',include('recomendador.urls')),
]

srswdom/recomendador/models.py
from django.db import models
import numpy as np

class TipoUsuario(models.Model):
	tipousuario = models.CharField(max_length=250,blank = True)
	descripciontipousuario = models.CharField(max_length=250,blank = True)

class Usuario(models.Model):
	#id 0,
	#•	Nombre de usuario
	#usuario = models.OneToOneField(User,on_delete=models.CASCADE)
	#nombreusuario = models.CharField(max_length=100,blank=True)
	#ipaddress 12.108.127.138,
	direccionip = models.GenericIPAddressField(default='0.0.0.0')
	#direccionip = models.CharField(max_length=50, default='0.0.0.0')
	#•	Tipo de usuario
	tipousuario = models.ForeignKey(TipoUsuario, on_delete = models.CASCADE)


	
class Proveedor(models.Model):
	#id
	#•	Nombre del proveedor
	nombreproveedor = models.CharField(max_length=250,blank = True)
	#•	Organización
	nombreorganizacion = models.CharField(max_length=250,blank = True)
	#•	Rango AS
	rangoas = models.CharField(max_length=250,blank = True)
	#•	Grado AS
	gradoas = models.CharField(max_length=250,blank = True)

class Dominio(models.Model):
	#id
	#•	Nombre 
	nombredominio = models.CharField(max_length=250,blank = True)
	
class Servicio(models.Model):
	#id 0
	##•	Dirección WSDL
	direccionwsdl = models.CharField(max_length=250,blank = True)
	#ipaddress 8.23.224.110,
	direccionip = models.GenericIPAddressField(default='0.0.0.0' )
	#Proveedor
#	proveedor = models.ForeignKey(Proveedor,on_delete = models.CASCADE)
	proveedor = models.CharField(max_length=250,blank = True)
	#Dominio
	dominio = models.ForeignKey(Dominio, on_delete = models.CASCADE)

	def calificacion_promedio(self):
		califacionesTodas = list(map(lambda x: x.calificacion, self.calificacion_set.all()))
		return np.mean(califacionesTodas)


class Calificacion(models.Model):
    OPCIONES_CALIFICACION = (
        (1, '1: Servicio Muy Mal recomendado'),
        (2, '2: Servicio Mal recomendado'),
        (3, '3: Servicio Regular'),
        (4, '4: Servicio recomendado'),
        (5, '5: Servicio Muy recomendado'),
    )
    servicio = models.ForeignKey(Servicio, on_delete = models.CASCADE)
    fecha_calificacion= models.DateTimeField('fecha de calificación')
    usuario = models.ForeignKey(Usuario,on_delete=models.CASCADE)
    calificacion = models.IntegerField(choices=OPCIONES_CALIFICACION)

srswdom/recomendador/forms.py
from django.forms import ModelForm, Textarea
from recomendador.models import Calificacion


class ReviewForm(ModelForm):
    class Meta:
       model = Calificacion
       #fields = ['rating', 'comment']
       fields = ['calificacion','usuario']
       #widgets = {            'comment': Textarea(attrs={'cols': 40, 'rows': 15}),        }

srswdom/recomendador/views.py
from django.shortcuts import get_object_or_404,render
from .models import Servicio, Usuario, Dominio, Calificacion
from django.http import HttpResponseRedirect
from django.urls import reverse
from .forms import ReviewForm
import datetime
#USUARIO
def lista_usuarios(request):
	lista_usuarios = Usuario.objects.order_by('id')
	context = {'lista_usuarios':lista_usuarios}
	return render(request,'recomendador/lista_usuarios.html',context)

def detalle_usuario(request, usuario_id):
    usuario = get_object_or_404(Usuario, pk=usuario_id)
    return render(request, 'recomendador/detalle_usuario.html', {'usuario': usuario})
#SERVICIO
def lista_servicios(request):
	lista_servicios = Servicio.objects.order_by('id')
	context = {'lista_servicios':lista_servicios}
	return render(request,'recomendador/lista_servicios.html',context)

def detalle_servicio(request, servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    form = ReviewForm()
    return render(request, 'recomendador/detalle_servicio.html', {'servicio': servicio,'form': form})

#@login_required
def nueva_calificacion(request, servicio_id):
    servicio = get_object_or_404(Servicio, pk=servicio_id)
    #usuario = get_object_or_404(Usuario, pk=usuario_id)
    form = ReviewForm(request.POST)
    if form.is_valid():
        cal = form.cleaned_data['calificacion']
        usuario = form.cleaned_data['usuario']
         #comentario = form.cleaned_data['comment']
        calificacion = Calificacion()
        calificacion.servicio = servicio
        calificacion.usuario = usuario
        print("cal",cal)
        calificacion.calificacion = cal
        #calificacion.comentario = comentario
        calificacion.fecha_calificacion = datetime.datetime.now()
        calificacion.save()
       # update_clusters()#Cuando una nueva reseña sea agregada, se actualizan los clusters
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('recomendador:detalle_servicio', args=(servicio_id,)))
    
    return render(request, 'recomendador/detalle_servicio.html', {'servicio': servicio,'form': form})


#PROVEEDOR

def lista_proveedores(request):
	lista_proveedores = Proveedor.objects.order_by('id')
	context = {'lista_proveedores':lista_proveedores}
	return render(request,'recomendador/lista_proveedores.html',context)

def detalle_proveedor(request, proveedor_id):
    context = {'proveedor_id':proveedor_id}
    return render(request, 'recomendador/detalle_proveedor.html',context)

#DOMINIO
def lista_dominios(request):
	lista_dominios = Dominio.objects.order_by('id')
	context = {'lista_dominios':lista_dominios}
	return render(request,'recomendador/lista_dominios.html',context)

def detalle_dominio(request, dominio_id):
    dominio = get_object_or_404(Dominio, pk=dominio_id)
    return render(request, 'recomendador/detalle_dominio.html', {'dominio': dominio})

#RECOMENDACION
def calificaciones(request):
	calificaciones = Calificacion.objects.order_by('id')
	context = {'calificaciones':calificaciones}
	return render(request,'recomendador/calificaciones.html',context)

srswdom/recomendador/templates/recomendador/calificaciones.html
{% extends 'base.html' %}
{% load saludo_tag %}

{% block title %}
<h2>Calificaciones</h2>
<h3>Numero de Calificaciones: {{calificaciones.count}}</h3>
{% endblock %}

{% block content %}
{% if calificaciones %}
<div class="row">
    {% for calificacion in calificaciones %}
    <div class="col-xs-6 col-lg-6">
        <h4>
        {{ calificacion.id }}
        </a></h4>
        <h5><p><b>Usuario:</b></p></h5>
        <ul>
            <li>Id: <a href="{% url 'recomendador:detalle_usuario' calificacion.usuario.id %}">{{ calificacion.usuario.id}}</a></li>
            <li>IP: {{calificacion.usuario.direccionip}}</li> 
            <li>Tipo de Usuario: {{calificacion.usuario.tipousuario.tipousuario}}</li>
        </ul>
            
        <h5><p><b>Servicio:</b></p></h5>
        <ul>
            <li>Id: <a href="{% url 'recomendador:detalle_servicio' calificacion.servicio.id %}">{{ calificacion.servicio.id }}</a></li>
            {% hello_world calificacion.servicio.proveedor as claveas %}
            <li>Proovedor: <a href="{% url 'recomendador:detalle_proveedor' claveas %}"> {{ calificacion.servicio.proveedor}}</a></li>
            <li><b>Dominio del servicio: </b>{{ calificacion.servicio.dominio.nombredominio }}</li>
        </ul>
        <h5><p><b>Calificacion: </b>{{ calificacion.calificacion }}</p></h5>
        <h5><p><b>Fecha: </b>{{ calificacion.fecha_calificacion }}</p></h5>
       
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No hay calificaciones disponibles.</p>
{% endif %}
{% endblock %}

srswdom/recomendador/templates/recomendador/detalle_dominio.html
{% extends 'base.html' %}

{% block title %}
<h2><a href="{% url 'recomendador:detalle_dominio' dominio.id %}">Nombre del dominio: {{ dominio.nombredominio }}</a></h2>
{% endblock %}

{% block content %}

{% endblock %}


	

srswdom/recomendador/templates/recomendador/detalle_proveedor.html
{% extends 'base.html' %}
{% load datos_tag %}

{% block title %}


{% endblock %}

{% block content %}
{% obtener_datos_asrank proveedor_id as valores %}

<p>Datos del proveedor</p>
<p><h1>As Number:{{ valores.asnumber }}</p></h1>
<p><b>As Nombre:</b>{{ valores.asname }}</p>
<p><b>Organización:</b>{{ valores.organization}}</p>
<p><b>AS Rank:</b>{{ valores.asRank }}</p>
<p><a href="{{ valores.url }}">URL: {{ valores.url }}</a></p>


{% endblock %}

srswdom/recomendador/templates/recomendador/detalle_servicio.html
{% extends 'base.html' %}
{% load saludo_tag %}
{% load bootstrap3 %}

{% block title %}
<h2><a href="{% url 'recomendador:detalle_servicio' servicio.id %}">Id del servicio: {{ servicio.id }}</a></h2>
<h5>{{ servicio.calificacion_set.count }} calificaciones ({{ servicio.calificacion_promedio | floatformat }} calificación promedio)</h5>
{% endblock %}

{% block content %}

{% hello_world servicio.proveedor as claveas %}
<p><b>Dirección WSDL: </b>{{ servicio.direccionwsdl }}</p>
<p><b>Dirección IP: </b>{{ servicio.direccionip }}</p>

<p>Proovedor: <a href="{% url 'recomendador:detalle_proveedor' claveas %}"> {{ servicio.proveedor}}</a></p>
<p><b>Dominio: </b>{{ servicio.dominio.nombredominio }}</p>

<p><b>Calificación promedio: </b>{{ servicio.dominio.nombredominio }}</p>




<h3>Calificaciones recientes</h3>

{% if servicio.calificacion_set.all %}
<div class="row">
    {% for cal in servicio.calificacion_set.all%}
    <div class="col-xs-6 col-lg-4">
          <h6>Calificación {{ cal.calificacion }} of 5 por  <b>Usuario:</b>
        <ul>
            <li>Id: <a href="{% url 'recomendador:detalle_usuario' cal.usuario.id %}">{{ cal.usuario.id}}</a></li>
            <li>IP: {{cal.usuario.direccionip}}</li> 
            <li>Tipo de Usuario: {{cal.usuario.tipousuario.tipousuario}}</li>
        </ul></h6>
        
    </div>
    {% endfor %}
</div>
{% else %}
<p>No hay calificaciones para este servicio todavia</p>
{% endif %}

<h3>Añadir calificación</h3>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'recomendador:nueva_calificacion' servicio.id %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form layout='inline' %}
    
    {% buttons %}
    <button type="submit" class="btn btn-primary">
      {% bootstrap_icon "star" %} Add
    </button>
    {% endbuttons %}

</form>

<h1>Recomendaciones </h1>
<h3>Filtro basado en contenido </h3>
{% endblock %}


	

srswdom/recomendador/templates/recomendador/detalle_usuario.html
{% extends 'base.html' %}
{% load saludo_tag %}

{% block title %}
<h2><a href="{% url 'recomendador:detalle_usuario' usuario.id  %}">Id del usuario: {{ usuario.id  }}</a></h2>
{% endblock %}

{% block content %}
<p>Dirección IP: {{ usuario.direccionip }}</p>
<p>Tipo de Usuario: {{ usuario.tipousuario.tipousuario }}</p>

<h3>Calificaciones recientes</h3>

{% if usuario.calificacion_set.all %}
<div class="row">
    {% for cal in usuario.calificacion_set.all%}
    <div class="col-xs-6 col-lg-4">
          <h6>Calificación {{ cal.calificacion }} de 5 al <b>servicio </b> 
          	<ul>
            <li>Id: <a href="{% url 'recomendador:detalle_servicio' cal.servicio.id %}">{{ cal.servicio.id }}</a></li>
            {% hello_world cal.servicio.proveedor as claveas %}
            <li>Proovedor: <a href="{% url 'recomendador:detalle_proveedor' claveas %}"> {{ cal.servicio.proveedor}}</a></li>
            <li><b>Dominio del servicio: </b>{{ cal.servicio.dominio.nombredominio }}</li>
        </ul></h6>
        
    </div>
    {% endfor %}
</div>
{% else %}
<p>No hay calificaciones para este servicio todavia</p>
{% endif %}

<h1>Recomendaciones </h1>
<h3>Filtro colaborativo basado en usuario </h3>


{% endblock %}

srswdom/recomendador/templates/recomendador/lista_dominios.html
{% extends 'base.html' %}

{% block title %}
<h2>Lista de Dominios</h2>
<h3>Numero de Dominios: {{lista_dominios.count}}</h3>
{% endblock %}

{% block content %}
{% if lista_dominios %}
<div class="row">
    {% for dominio in lista_dominios %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'recomendador:detalle_dominio' dominio.id %}">
        {{ dominio.nombredominio }}
        </a></h4>
      
       
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No hay dominios disponibles.</p>
{% endif %}
{% endblock %}


srswdom/recomendador/templates/recomendador/lista_proveedores.html
{% extends 'base.html' %}

{% block title %}
<h2>Lista de Proveedores</h2>
{% endblock %}

{% block content %}
{% if lista_proveedores %}
<div class="row">
    {% for proveedor in lista_proveedores %}
    <div class="col-xs-6 col-lg-4">
        <h4><a href="{% url 'recomendador:detalle_proveedor' proveedor.id %}">
        {{ proveedor.nombreproveedor }}
        </a></h4>
        <h5><p><b>Nombre de la organización:</b>{{ proveedor.nombreorganizacion }}</p></h5>
        <h5><p><b>Rango AS:</b>{{ proveedor.rangoas }}</p></h5>
        <h5><p><b>Grado AS:</b>{{ proveedor.gradoas }}</p></h5>
       
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No hay proveedors disponibles.</p>
{% endif %}
{% endblock %}


srswdom/recomendador/templates/recomendador/lista_servicios.html
{% extends 'base.html' %}
{% load saludo_tag %}

{% block title %}
<h2>Lista de Servicios</h2>
<h3>Numero de Servicios: {{lista_servicios.count}}</h3>
{% endblock %}

{% block content %}

{% if lista_servicios %}



    


<div class="row">
    {% for servicio in lista_servicios %}

    <div class="col-xs-6 col-lg-6">
        <h4><a href="{% url 'recomendador:detalle_servicio' servicio.id %}">
        {{ servicio.id }}
        </a></h4>

        {% hello_world servicio.proveedor as claveas %}
        
        
        <h5><p><b>Dirección WSDL: </b>{{ servicio.direccionwsdl }}</p></h5>
        <h5><p><b>Dirección IP: </b>{{ servicio.direccionip }}</p></h5>
        <h5>Proovedor: <a href="{% url 'recomendador:detalle_proveedor' claveas %}"> {{ servicio.proveedor}}</a></h5>
      
        <h5><p><b>Dominio del servicio: </b>{{ servicio.dominio.nombredominio }}</p></h5>
       
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No hay Servicios disponibles.</p>
{% endif %}
{% endblock %}


srswdom/recomendador/templates/recomendador/lista_usuarios.html

{% extends 'base.html' %}

{% block title %}
<h2>Lista de Usuarios</h2>
<h3>Numero de Usuarios: {{lista_usuarios.count}}</h3>
{% endblock %}

{% block content %}
{% if lista_usuarios %}

<div class="row">
    {% for usuario in lista_usuarios %}
    <div class="col-xs-6 col-lg-6">
        <h4><a href="{% url 'recomendador:detalle_usuario' usuario.id %}">
        {{ usuario.id }}
        </a></h4>
        <p><b>Dirección IP: </b>{{ usuario.direccionip }}</p>
		<p><b>Tipo de usuario: </b>{{ usuario.tipousuario.tipousuario }}</p>
	
       
    </div>
    {% endfor %}
</div>
{% else %}
    <p>No hay usuarios disponibles.</p>
{% endif %}
{% endblock %}


srswdom/templates/base.html
{% load bootstrap3 %}

{% bootstrap_css %}
{% bootstrap_javascript %}

{% block bootstrap3_content %}
<div class="container">
    <nav class="navbar navbar-default">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'recomendador:lista_usuarios' %}">SRSWDOM</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'recomendador:lista_usuarios' %}">Lista de Usuarios</a></li>
                <li><a href="{% url 'recomendador:lista_servicios' %}">Lista de Servicios</a></li>
                <li><a href="{% url 'recomendador:lista_dominios' %}">Lista de Dominios</a></li>
                <li><a href="{% url 'recomendador:calificaciones' %}">Calificaciones</a></li>
                <li><a href="{% url 'recomendador:lista_usuarios' %}">Home</a></li>
            </ul>
            
        </div>
    </nav>
    

    <h1>{% block title %}(no title){% endblock %}</h1>

    {% bootstrap_messages %}

    {% block content %}(no content){% endblock %}
</div>

{% endblock %}